In [8]:
# Import NumPy

import numpy as np

In [2]:
# Checking NumPy Version

print(np.__version__)

1.26.4


In [6]:
# Creating a NumPy Array

arr = np.array([5,4,3,2,1])
print(arr)

[5 4 3 2 1]


In [5]:
arr = np.array([5,4,3,2,1])

print(arr)

print(type(arr))

[5 4 3 2 1]
<class 'numpy.ndarray'>


In [12]:
list = [1,2,3]

print ("list in python :", list)

list in python : [1, 2, 3]


In [67]:
# Use a tuple to create a NumPy array

arr = np.array((1, 2, 3))

print(arr)

print(type(arr))

[1 2 3]
<class 'numpy.ndarray'>


In [ ]:
arr = np.array([5,4,3,2,1])

print(arr)

print(type(arr))

In [11]:
# Use a tuple to create a NumPy array

arr = np.array((5,4,3,2,1))

print(arr)

print(type(arr))

[5 4 3 2 1]
<class 'numpy.ndarray'>


**Dimensi**

Dimensi in Array

A dmension in arrays is one level of array depth (nested arrays)

In [11]:
# 0-D array

arr = np.array(42)
print(arr)

42


In [25]:
# Create a 1-D array containing one array

a = np.array([10, 20, 30])
print(a)
print(a.ndim)

[10 20 30]
1


In [26]:
# Create a 2-D array containing two array

b = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 60]])
print(b)
print(b.ndim)

[[10 20 30]
 [40 50 60]
 [70 80 60]]
2


In [27]:
# Create a 3-D array containing two array, both containing two array

c = np.array([[[10, 20, 30], [40, 50, 60]],[[70, 80, 90], [100, 110, 120]]])
print(c)
print(c.ndim)

[[[ 10  20  30]
  [ 40  50  60]]

 [[ 70  80  90]
  [100 110 120]]]
3


In [24]:
# Check how many dimensi the array have

a = np.array(10)
b = np.array([10, 20, 30])
c = np.array([[10, 20, 30]])
d = np.array([[[10, 20, 30]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [39]:
# Create on array with 7 dimensions and verify that it has 7 dimension

arr_1 = np.array([1, 2, 3, 4, 5, 6], ndmin=7)

print(arr_1)
print('jumlah dimensi :', arr_1.ndim)
print(arr_1[0])

[[[[[[[1 2 3 4 5 6]]]]]]]
jumlah dimensi : 7
[[[[[[1 2 3 4 5 6]]]]]]


In [34]:
# Create the first element from the following array

arr = np.array([10, 20, 30, 40])
print(arr[0])

10


In [35]:
# Get the second element from the following array

arr = np.array([10, 20, 30, 40])
print(arr[1])

20


In [36]:
# Get third and fourth element from the array and add them 

arr = np.array([10, 20, 30, 40])
print(arr[2] + arr[3])

70


In [41]:
# Access the element on the first row, second coumn

arr = np.array([[10, 20, 30, 40, 50], [60, 70, 80, 90, 100]])
print('2nd element on 1st row :', arr[0,1])

2nd element on 1st row : 20


In [42]:
# Access the element on the 2nd row, 5th column

arr = np.array([[10, 20, 30, 40, 50],[60, 70, 80, 90, 100]])
print('5th element on 2nd row :', arr[1, 4]) #[row, elemen]

5th element on 2nd row : 100


In [43]:
# Access the third element of the second array of the first array

arr = np.array([[[10, 20, 30],[40, 50, 60]],[[70, 80, 90],[100, 110, 120]]])
print(arr[1,0,2]) #[dim, row, element]

90


## TASK

**Task 1**

In [3]:
# checking Numpy Vrsion

# print(np.__version__

In [5]:
#Numpy form list

list = [10, 20, 30]
print("List in Python :", list)

List in Python : [10, 20, 30]


In [10]:
# Numpy form Tuple

# arr = np.aray(("Aswina", 10, 20, 30))
# bprint(arr)
# print(type(arr))

**Task 2**

Create 3 different dimension and check the dimension

In [13]:
# Create 3 different dimension and check the dimension

a = np.array([10, 20, 30])
print(a)
print(a.ndim)

[10 20 30]
1


In [65]:
# Access the four element of the second array of the first array

arr = np.array([[[10, 20, 30],[40, 50, 60]],[[70, 80, 90],[100, 110, 120]]])
print(arr[1, 1, 1])

110


In [66]:
# Use a tuple to create a NumPy array

arr = np.array(("Aswinah", 1, 2, 3))

print(arr)

print(type(arr))

['Aswinah' '1' '2' '3']
<class 'numpy.ndarray'>
