import library-library yang di perlukan

In [5]:
import pandas as pd
import numpy as np

pandas mempunyai dua objektif yaitu Series dan Data Frame

## Object Series

Oject Series mempunyai satu dimensi data. Tidak mempunyai nama column karena hanya memiliki satu column saja dan mempunyai index

In [3]:
data = [0, 1, 2, 3, 4]

In [4]:
print(data)

[0, 1, 2, 3, 4]


mengubah data ke dalam bentuk Series

In [5]:
data = pd.Series(data)

data

0    0
1    1
2    2
3    3
4    4
dtype: int64

Convert dari series menjadi array

In [6]:
data.values

array([0, 1, 2, 3, 4], dtype=int64)

In [ ]:
array([0.25, 0.5, 0.75, 1.])

**menampilkan indeks**

index berupa range dimana titik start nya itu inklusif dalam range dari titk stop nya itu ekslusif dari range

In [8]:
data.index

RangeIndex(start=0, stop=5, step=1)

In [10]:
list(range(1,10))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

cara memanggil data

In [11]:
data[2]

2

index implisit adalah index default nya

kita bisa mendefinisikan index nya, ini di sebut index eksplisit yaitu index yang di defined

ketika mendefinisikan index, jumlah index harus sama dengan jumlah data nya

In [12]:
data = pd.Series([0.25, 0.50, 0.75, 1], index =['a','b','c','d'])

In [13]:
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [14]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [13]:
data.index

Index(['a', 'b', 'c', 'd'], dtype='object')

panggil data nya

In [14]:
# index eksplisit

data['a']

0.25

**ini adalah data selection**

walaupun kita sudah membuat indeks eksplisit, kita masih bisa memanggil indeks implisit nya

In [15]:
# index implisit

data[3]

C:\Users\Win 10\AppData\Local\Temp\ipykernel_8160\2136116981.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  data[3]


1.0

ketika indeks implisit dan indeks ekspliist nya ada yang sama,, ketika kita memanggil data nya, maka dia hanya akan mengandalkan indeks ekplisit nya

In [18]:
data_2 = pd.Series([0.25, 0.50, 0.75, 1], index=[2,3,5,7])

In [21]:
# indeks ekplisit

data_2[2]

0.25

In [22]:
# indeks impliit

data_2[0]

KeyError: 0

**kita akan coba melakukan data slicing**

In [34]:
data = pd.Series([0.25, 0.50, 0.75, 1], index=['a', 'b', 'c', 'd'])

In [35]:
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

misalnya kita akan memanggil dari data b sampai data c

In [37]:
data['b' :'c'] #indeks eksplisit

b    0.50
c    0.75
dtype: float64

tapi bila kita slicing indeks implisit nya, maka hanya akan muncul titik start nya. karena indeks implisit berupa range

In [38]:
data[1:2] #indeks implisit

b    0.5
dtype: float64

## loc dan iloc

contoh data yang index implisit dan index explisit nya ada yang sama

In [17]:
data_2 = pd.Series([0.25, 0.50, 0.75, 1], index=[2,3,5,7])

In [18]:
data_2

2    0.25
3    0.50
5    0.75
7    1.00
dtype: float64

ketika kita akses satu index maka yang muncul adalah index ekplisit nya

In [19]:
data_2[2] #index eksplisit : slicing

0.25

ketika kita panggil index eskplisit dari index 2 samapi index 3. nilai yang muncul justru dari index implisit nya

In [20]:
data_2[2:3] #index implisit : slicing

5    0.75
dtype: float64

ketika index eksplisit dan index implisit ada yang sama maka akan terjadi inkonsistensi seperti case di atas

untuk mengatasi keadaan inkonsistensi tersebut maka kita akan gunakan kaidah loc iloc

**loc adaah untuk memanggil index eksplisit nya**

**iloc adalah untuk memanggil index implisit nya**

In [24]:
# loc

data_2.loc[3] #selecting index eksplisit

0.5

In [25]:
data_2.loc[2:3] #selecting index eksplisit

2    0.25
3    0.50
dtype: float64

In [27]:
#iloc

data_2.iloc[0] #selecting index implisit

0.25

In [28]:
data_2.iloc[3] #selecting index implisit

1.0

In [29]:
data_2.iloc[2:3] #selecting index implisit

5    0.75
dtype: float64

## Data Frame

In [30]:
dict_populasi = {'jakarta' : 750,
                 'Bogor' : 490,
                 'Pandeglang' : 123,
                 'Banten' : 456,
                 'Serang' : 789}

#ini hanya permisalan, bukan angka populasi yang sesungguhnya

In [31]:
dict_populasi

{'jakarta': 750, 'Bogor': 490, 'Pandeglang': 123, 'Banten': 456, 'Serang': 789}

In [34]:
# transformasi dictionary ke Series

populasi = pd.Series(dict_populasi)

In [35]:
populasi

jakarta       750
Bogor         490
Pandeglang    123
Banten        456
Serang        789
dtype: int64

In [36]:
populasi.loc['Pandeglang']

123

In [37]:
populasi.iloc[2]

123

In [38]:
dict_luas = {'jakarta' : 750,
                 'Bogor' : 490,
                 'Pandeglang' : 123,
                 'Banten' : 456,
                 'Serang' : 789}

#ini hanya permisalan, bukan angka luas yang sesungguhnya

In [40]:
dict_luas

{'jakarta': 750, 'Bogor': 490, 'Pandeglang': 123, 'Banten': 456, 'Serang': 789}

In [41]:
# transformasi dictionary ke Series

luas = pd.Series(dict_luas)

In [42]:
luas

jakarta       750
Bogor         490
Pandeglang    123
Banten        456
Serang        789
dtype: int64

In [43]:
daerah = pd.DataFrame({'pop':populasi, 'luas daerah':luas})

In [44]:
daerah

pop  luas daerah
jakarta     750          750
Bogor       490          490
Pandeglang  123          123
Banten      456          456
Serang      789          789

In [45]:
daerah['luas daerah']

jakarta       750
Bogor         490
Pandeglang    123
Banten        456
Serang        789
Name: luas daerah, dtype: int64

In [46]:
daerah['luas daerah']['jakarta']

750

## Task

**Task 1**

In [3]:
# Checking NumPy Version

print(np.__version__)

In [7]:
# Numpy from list

list = [10, 20, 30]
print("List in python :", list)

List in python : [10, 20, 30]


In [11]:
# NumPy from Tuple

arr = np.array(("Aswinah", 1, 2, 3))
                
print(arr)
                
print(type(arr))

['Aswinah' '1' '2' '3']
<class 'numpy.ndarray'>


**Task 2**
- membuat Series
- membuat indeks eksplisit (custom)
- memanggil indeks eksplisit
- panggil indeks implisit (default)

In [27]:
# Customer index

ood_number = pd.Series([1, 3, 5, 7, 9], index=['e', 'f', 'g', 'h', 'i'])

In [28]:
ood_number

e    1
f    3
g    5
h    7
i    9
dtype: int64

In [29]:
ood_number.values

array([1, 3, 5, 7, 9], dtype=int64)

In [30]:
ood_number.index

Index(['e', 'f', 'g', 'h', 'i'], dtype='object')

In [31]:
# indeks eksplisit

ood_number['h']

7

In [32]:
# index implisit

ood_number[2]

C:\Users\Win 10\AppData\Local\Temp\ipykernel_1900\828689558.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  ood_number[2]


5

**Task 3**
- membuat Series
- membuat indeks eksplisit (custom) ada kesamaan dengan index default
- memanggil indeks eksplisit
- panggil indeks implisit (default)

In [39]:
names = ['Aswin', 'Andhito', 'Alnima', 'Shafira', 'Laksmi']
data = [100, 200, 300, 400, 500]
names_with_data = pd.Series(names, index=data)

In [41]:
print(names_with_data)

100      Aswin
200    Andhito
300     Alnima
400    Shafira
500     Laksmi
dtype: object


In [42]:
names_with_data.values

array(['Aswin', 'Andhito', 'Alnima', 'Shafira', 'Laksmi'], dtype=object)

In [43]:
names_with_data.index

Index([100, 200, 300, 400, 500], dtype='int64')

In [44]:
# index explisit

names_with_data[100]

'Aswin'

In [45]:
# index implisit

names_with_data[2]

KeyError: 2

**Task 4**
- membuat Series
- membuat indeks eksplisit 
- panggil slicing eksplisit
- panggil slicing implisit

In [46]:
data = [10, 20, 30, 40, 50]
index_labels = ['A', 'B', 'C', 'D', 'E']
series = pd.Series(data, index=index_labels)

In [47]:
print(series)

A    10
B    20
C    30
D    40
E    50
dtype: int64


In [48]:
# slicing using explicit index labels

slicel = series['B':'D'] # slicing from index 'B' to 'D' (inclusive)
print("Slice using explicit index labels :")
print(slicel)

Slice using explicit index labels :
B    20
C    30
D    40
dtype: int64


In [49]:
# slicing using implicit integer index

slice2 = series[0:1] #slicing from index position 0 to 1 (excusive)
print("Slice using implicit Integer index :")
print(slice2)

Slice using implicit Integer index :
A    10
dtype: int64


**Task 5**
- Membuat series
- Membuat index eksplicit
- Panggil loc
- Panggil iloc

In [52]:
#Create a Series

ood_number = [1, 3, 5, 7, 9]
ood_number = pd.Series(ood_number)

print(ood_number)

0    1
1    3
2    5
3    7
4    9
dtype: int64


In [53]:
# create index explicit

ood_number2 = pd.Series([1, 3, 5, 7, 9], index=[3, 5, 1, 8, 7])

In [55]:
#memanggil loc

ood_number2.loc[3:1]

3    1
5    3
1    5
dtype: int64

In [57]:
#memanggil iloc

ood_number2.iloc[0:2]

3    1
5    3
dtype: int64

**Task 6**
- membuat Series menggunakan dictionary
- panggil loc
- panggil iloc

In [59]:
dict_snack = {'Biskuit':20,
              'Bengbeng':51,
              'Tango':37,
              'Nabati':29}

In [60]:
dict_snack

{'Biskuit': 20, 'Bengbeng': 51, 'Tango': 37, 'Nabati': 29}

In [63]:
#transformasi dictionary ke Series

snack = pd.Series(dict_snack)

In [64]:
snack

Biskuit     20
Bengbeng    51
Tango       37
Nabati      29
dtype: int64

In [65]:
snack.loc['Tango']

37

In [66]:
snack.iloc[0]

20